author: "tensorknower69"
category: Web
copyright: "2020 tensorknower69"
github: "tensorknower69/nhentai"
license: MIT
maintainer: "tensorknower69 <62006583+tensorknower69@users.noreply.github.com>"
name: "nhentai"
synopsis: "Scrape/download nhentai galleries and JSONs"
version: 0.1.3.0

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - aeson
  - base >= 4.7 && < 5
  - errors
  - exceptions
  - lens
  - modern-uri
  - refined
  - scalpel-core
  - scientific
  - split
  - tagsoup
  - template-haskell
  - text
  - time

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Wno-tabs
    - -Wno-name-shadowing

executables:
  nhentai:
    main: NHentai/Main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -Wno-tabs
      - -Wno-orphans
      - -Wno-unused-matches
      - -Wno-name-shadowing
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - bytestring
      - directory
      - filepath
      - http-client
      - http-client-tls
      - http-types
      - monad-logger
      - mtl
      - network-uri
      - nhentai
      - optparse-applicative
      - random
      - streaming
      - unliftio

tests:
  nhentai-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -Wall
      - -Wno-tabs
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nhentai
      - scalpel
      - tasty-hunit
      - tasty
      - http-client
      - http-client-tls
